language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
dist: bionic
matrix:
  exclude:
    - os: linux
      compiler: clang
env:
  - SUBTARGET=tiny   MAME=mametiny64
script:
  - make -j4 -f Makefile.libretro OPTIMIZE=0 PTR64=1;
sudo: required
before_install:
  - "sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y --force-yes gcc-9 g++-9 libsdl2-dev libsdl2-ttf-dev libasound2-dev libxinerama-dev libxi-dev qt5-default"
branches:
  only:
    - master
notifications:
  email: false
