name: MAME-libretro Android ARMv8a

on:
  push:
    branches:
      - master

jobs:
  AndroidARM64:
    name: Build for Android ARM64
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "21.3.6528147"
      ANDROID_NDK_ROOT:    ${ANDROID_HOME}/ndk/${ANDROID_NDK_VERSION}
      ANDROID_NDK_LLVM:    ${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64
      ANDROID_NDK_ARM:     ${ANDROID_NDK_ROOT}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
      ANDROID_NDK_ARM64:   ${ANDROID_NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64

    steps:    
    - name: Install Android NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}"
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      run: |
        make -f Makefile.libretro platform=android-arm64 -j8
        /usr/local/lib/android/sdk/ndk/${ANDROID_NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/aarch64-linux-android/bin/strip -s mame_libretro_android.so
        zip -9 mame_libretro_android.so.zip mame_libretro_android.so
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Android_ARM64
        prerelease: false
        title: Android ARM64
        files: |
          mame_libretro_android.so.zip
    - name: Save core for upload job
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro_android.so.zip
        path: mame_libretro_android.so.zip
  
  uploadToBB:
    name: Upload core to buildbot
    runs-on: ubuntu-latest
    needs: AndroidARM64
    
    steps:
    - name: Recover core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: mame_libretro_android.so.zip
        path: .
    - name: Upload to buildbot
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
      with:
        flags: '-vazr --delete'
        options: ''
        ssh_options: '-p ${{ secrets.PORT }}'
        src: mame_libretro_android.so.zip
        dest: '${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.ANDROID_ARM64_PATH }}'
