name: CI (Libretro - macOS)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build
        run: |
          make -f Makefile.libretro \
            platform=osx \
            -j$(sysctl -n hw.ncpu)
