name: MAME-libretro Nightly Builds

on:
  push:
    branches:
      - master

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: rm -rf .git # try to save some space so we don't run out
    - run: sudo apt install build-essential mesa-common-dev
    - run: make -f Makefile.libretro -j4 ; make -f Makefile.libretro -j4
    - run: strip -s mame_libretro.so
    - run: zip -9 mame_libretro.zip mame_libretro.so
    - name: Upload MAME core
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mame_libretro.zip
        tag: Linux_64-bit
        asset_name: mame_libretro.zip
        overwrite: true
        
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - run: msys2do pacman -S --noconfirm --disable-download-timeout --needed wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - uses: actions/checkout@v2
    - run: msys2do rm -rf .git # try to save some space so we don't run out
    - run: msys2do make -f Makefile.libretro -j4 ; msys2do make -f Makefile.libretro -j4
    - run: strip.exe -s mame_libretro.dll
    - run: msys2do zip -9 mame_libretro.zip mame_libretro.dll
    - name: Upload MAME core
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mame_libretro.zip
        tag: Windows_64-bit
        asset_name: mame_libretro.zip
        overwrite: true
