name: MAME-libretro Linux x86_64

on:
  push:
    branches:
      - master

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install build-essential mesa-common-dev binutils
    - run: make -f Makefile.libretro -j8
    - run: strip -s mame_libretro.so
    - run: zip -9 mame_libretro.zip mame_libretro.so
    - name: Upload MAME core
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Linux_64-bit
        prerelease: false
        title: Linux x86_64
        files: |
          mame_libretro.zip

