name: MAME-libretro macOS x86_64

on:
  push:
    branches:
      - master

jobs:
  MacOS:
    name: Build for macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: make -f Makefile.libretro -j8
    - run: zip -9 mame_libretro.zip mame_libretro.dylib
    - name: Upload MAME core
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: macOS-x86_64
        prerelease: false
        title: macOS x86_64
        files: |
          mame_libretro.zip
