name: MAME-libretro Windows x86_64

on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - run: msys2do pacman -S --noconfirm --disable-download-timeout --needed wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - uses: actions/checkout@v2
    - run: msys2do make -f Makefile.libretro -j8
    - run: strip.exe -s mame_libretro.dll
    - run: msys2do zip -9 mame_libretro.zip mame_libretro.dll
    - name: Upload MAME core
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mame_libretro.zip
        tag: Windows_64-bit
        asset_name: mame_libretro.zip
        overwrite: true
